#version: '3.8'
services:
  #app:
    #container_name: clicala_app
    #image: sua-imagem-app
    #build: .
    #ports:
    #  - '3000:3000'
    #depends_on:
    #  - postgres
   #   - mongo
    #environment:      
    #  POSTGRES_USER: postgres
    #  POSTGRES_PASSWORD: docker
    #  POSTGRES_DB: clica-la_db
    #  PGDATA: /data/postgres
    #volumes:
    #  - .:/usr/src/app
    #command: pnpm run start:dev

  postgres:
    container_name: clica-la_db-pg
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: clica-la_db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  mongo:
    environment:
      MONGODB_URI: 'mongodb://mongo:27017/nest'
      MONGODB_NAME: mongodb_database
      MONGODB_USER: mongodb_user
      MONGODB_PASS: mongo_docker
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    external: false
